server:
  port: 8080

spring:
  application:
    name: customer
  jpa:
    generate-ddl: true
  datasource:
    username: 'user'
    url: jdbc:postgresql://localhost:5432/customer?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: create
        show-sql: 'true'